
openvar('oCanada.deaths')
openvar('oOntario.deaths')
openvar('oOttawa.deaths')
openvar('oQuebec.deaths')
openvar('oBC.deaths')
openvar('oChina.deaths')
openvar('oDenmark.deaths')
openvar('oFrance.deaths')
openvar('oGermany.deaths')
openvar('oItaly.deaths')
openvar('oSKorea.deaths')
openvar('oSpain.deaths')
openvar('oSweden.deaths')
openvar('oUSA.deaths')
openvar('oNewYork.deaths')
